# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
        - id: check-byte-order-marker
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-symlinks
        - id: check-yaml
        - id: end-of-file-fixer
        - id: mixed-line-ending
        - id: trailing-whitespace
-   repo: local
    hooks:
        - id: fmt
          name: cargo fmt
          description: Runs cargo fmt
          entry: cargo fmt --all
          pass_filenames: false
          language: rust
          types: [ rust ]

        - id: update-notice
          name: update Notice file
          pass_filenames: false
          description: Update notice
          entry: echo "This project wouldn't be possible without the following amazing dependencies:\n" > NOTICE && cargo license >> NOTICE
          language: system
          types: [ text ]

        - id: check-spdx
          name: check SPDX
          description: Check SPDX license headers
          entry: scripts/check_copyright.sh
          language: script
          types: [ rust ]
