[package]
name = "libary"
version = "0.1.0"
edition = "2021"


[dependencies]
sha3 = "0.10.8"

[dependencies.oqs]
# Until https://github.com/open-quantum-safe/liboqs-rust/pull/259 is merged, we directly pull from https://github.com/Scarjit/liboqs-rust
git = "https://github.com/Scarjit/liboqs-rust"
default-features = false
features = ["kyber", "dilithium", "serde", "vendored"]

[dependencies.anyhow]
version = "1.0.81"
default-features = false
