name: rust test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: wasm32-unknown-emscripten, x86_64-unknown-linux-gnu
          components: rustfmt, clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests on x86_64-unknown-linux-gnu
        run: cargo test --target x86_64-unknown-linux-gnu
      - name: Run tests on wasm32-unknown-emscripten
        run: cargo test --target wasm32-unknown-emscripten
