name: rust test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, wasm32-unknown-emscripten]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}
          components: rustfmt, clippy

      - name: Install build-essential
        if: matrix.target == 'wasm32-unknown-emscripten'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential gcc-multilib

      - uses: mymindstorm/setup-emsdk@v14
        if: matrix.target == 'wasm32-unknown-emscripten'

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --target ${{ matrix.target }}
